[package]
name = "algo-graph"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
publish = false

[[bin]]
name = "algo-graph"
path = "src/main.rs"

[dependencies]
clap.workspace = true
k-rust = { path = "../k-rust", default-features = false }
k-rust-kore.workspace = true
proc-macro2 = { version = "1.0", features = ["span-locations"] }
quote = "1.0"
serde.workspace = true
serde_json.workspace = true
strsim = "0.11"
syn = { version = "2.0", features = ["full", "visit"] }
toml.workspace = true

[dev-dependencies]
insta.workspace = true

[[test]]
name = "freshness"
harness = false
