[package]
name = "k-rust-napi"
version = "0.3.0"
edition = "2024"
rust-version = "1.85"
description = "Node-API bindings for the k-rust frontend"
repository = "https://github.com/midnightntwrk/k-rust"
license = "BSD-3-Clause"
publish = false

[lib]
crate-type = ["cdylib"]
doctest = false
test = false

[dependencies]
k-rust = { path = "../k-rust" }
napi.workspace = true
napi-derive.workspace = true

[build-dependencies]
napi-build.workspace = true
