/-
`lake exe krust-audit`: the axiom audit behind `scripts/lean-check.sh`.

It imports the built `KRust` library, enumerates every declaration whose module is `KRust` or
lies under `KRust.`, and fails when
  * any such declaration depends on `sorryAx` (written `sorry` or `admit`, or an elaboration
    error that Lean replaced by `sorry`),
  * any such declaration is an `axiom` (assumptions are named hypotheses of theorems), or
  * any such theorem depends on an axiom other than `propext`, `Classical.choice`, `Quot.sound`
    (for example an `axiom` added by a module).
The declarations are read from the environment, not from a hand-kept list.

`lake exe krust-audit --theorems FILE` also writes the sorted names of the theorems a person
wrote in a `KRust` module, one per line, to FILE. A theorem counts when it has a source range,
its name is not an internal detail (`_private`, `proof_`, `match_`, `eq_1`, …), and it is not
a reserved name (equation lemmas such as `eq_def`); this drops what Lean generates (`injEq`,
`sizeOf_spec`, `brecOn`). `scripts/lean-check.sh` compares that output with the tracked
`lean/theorems.txt`, which algorithm cards name in their `lean` key.
Exit codes: 0 ok, 1 check failed, 2 usage error.
-/
import Lean

open Lean

/-- The axioms a `KRust` theorem may depend on: the three axioms of Lean's standard foundations. -/
def allowedAxioms : List Name := [``propext, ``Classical.choice, ``Quot.sound]

/-- Whether a module belongs to the `KRust` library. -/
def isKRustModule (module : Name) : Bool :=
  module == `KRust || (`KRust).isPrefixOf module

/-- Whether a theorem was written in a source file rather than generated by Lean. -/
def isWrittenTheorem (env : Environment) (name : Name) : Bool :=
  !name.isInternalDetail && !isReservedName env name
    && (declRangeExt.find? (level := .exported) env name).isSome

def main (args : List String) : IO UInt32 := do
  let theoremsFile ← match args with
    | [] => pure none
    | ["--theorems", file] => pure (some file)
    | _ => do
      IO.eprintln "usage: krust-audit [--theorems FILE]"
      return 2
  initSearchPath (← findSysroot)
  let env ← importModules #[{ module := `KRust }] {} (trustLevel := 0)
  let mut failures : Array String := #[]
  let mut theorems := 0
  let mut declarations := 0
  let mut written : Array Name := #[]
  for (name, info) in env.constants.map₁.toList do
    let some moduleIdx := env.getModuleIdxFor? name | continue
    let some module := env.header.moduleNames[moduleIdx.toNat]? | continue
    unless isKRustModule module do continue
    declarations := declarations + 1
    let (axioms, _) ← (collectAxioms name : CoreM (Array Name)).toIO
      { fileName := "<krust-audit>", fileMap := default } { env }
    if axioms.contains ``sorryAx then
      failures := failures.push s!"{name} ({module}) uses sorry"
    if let .axiomInfo _ := info then
      failures := failures.push s!"{name} ({module}) is an axiom; state it as a named hypothesis"
    if let .thmInfo _ := info then
      theorems := theorems + 1
      if isWrittenTheorem env name then
        written := written.push name
      let extra := axioms.filter (fun ax => ax != ``sorryAx && !allowedAxioms.contains ax)
      unless extra.isEmpty do
        failures := failures.push s!"{name} ({module}) depends on axioms {extra.toList}"
  if declarations == 0 then
    IO.eprintln "krust-audit: no declarations found in the KRust modules"
    return 1
  for failure in failures do
    IO.eprintln s!"krust-audit: {failure}"
  if let some file := theoremsFile then
    let names := (written.map toString).qsort (· < ·)
    IO.FS.writeFile file (String.join (names.toList.map (· ++ "\n")))
  if failures.isEmpty then
    IO.println s!"krust-audit: ok, {declarations} declarations, {theorems} theorems, axioms within {allowedAxioms}"
    return 0
  return 1
