use std::collections::{BTreeMap, BTreeSet};

use crate::{Graph, Node};

/// Filters shared by the static Mermaid projections.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct Filters {
    pub areas: Vec<String>,
    pub phases: Vec<String>,
    pub counters: Vec<String>,
}

/// Render ordered phases and the algorithms whose sites their calls name.
pub fn render_pipeline(graph: &Graph, filters: &Filters) -> String {
    let node_by_id = node_map(graph);
    let selected_algorithms = selected_algorithms(graph, filters, &node_by_id);
    let phase_filter_active = !filters.phases.is_empty();
    let mut phases = graph
        .nodes
        .iter()
        .filter(|node| node.kind == "phase")
        .filter(|phase| !phase_filter_active || matches_any(&phase.id, &filters.phases))
        .filter(|phase| {
            let contains_selected = || {
                graph.edges.iter().any(|edge| {
                    edge.kind == "contains"
                        && edge.from == phase.id
                        && selected_algorithms.contains(&edge.to)
                })
            };
            if !filters.counters.is_empty() {
                contains_selected()
            } else if !filters.areas.is_empty() {
                filters
                    .areas
                    .iter()
                    .any(|area| phase.area.as_deref() == Some(area.as_str()))
                    || contains_selected()
            } else {
                true
            }
        })
        .collect::<Vec<_>>();
    phases.sort_by_key(|phase| phase.sequence.unwrap_or(usize::MAX));
    let phase_ids = phases
        .iter()
        .map(|phase| phase.id.clone())
        .collect::<BTreeSet<_>>();

    let contains = graph
        .edges
        .iter()
        .filter(|edge| {
            edge.kind == "contains"
                && phase_ids.contains(&edge.from)
                && selected_algorithms.contains(&edge.to)
        })
        .collect::<Vec<_>>();
    let algorithm_ids = contains
        .iter()
        .map(|edge| edge.to.clone())
        .collect::<BTreeSet<_>>();

    let mut visible = phases.to_vec();
    visible.extend(
        algorithm_ids
            .iter()
            .filter_map(|id| node_by_id.get(id).copied()),
    );
    visible.sort_by(|left, right| left.id.cmp(&right.id));
    let mermaid_ids = mermaid_ids(visible.iter().copied());

    let mut output = String::new();
    output.push_str("%% generated by algo-graph; edge labels include provenance\n");
    output.push_str("flowchart TD\n");
    for phase in &phases {
        let id = &mermaid_ids[&phase.id];
        let table = phase.table.as_deref().unwrap_or("phase table");
        let call = phase
            .call
            .as_deref()
            .map(|call| format!("<br/>call: {}", label(call)))
            .unwrap_or_default();
        output.push_str(&format!(
            "  {id}[\"{}<br/>{table}{call}\"]\n",
            label(&phase.id)
        ));
    }
    for algorithm_id in &algorithm_ids {
        let algorithm = node_by_id[algorithm_id];
        output.push_str(&format!(
            "  {}([\"{}\"])\n",
            mermaid_ids[algorithm_id],
            label(&algorithm.id)
        ));
    }
    for edge in graph.edges.iter().filter(|edge| {
        edge.kind == "follows" && phase_ids.contains(&edge.from) && phase_ids.contains(&edge.to)
    }) {
        output.push_str(&format!(
            "  {} -->|\"follows [table]\"| {}\n",
            mermaid_ids[&edge.from], mermaid_ids[&edge.to]
        ));
    }
    for edge in contains {
        output.push_str(&format!(
            "  {} -.->|\"contains [{}]\"| {}\n",
            mermaid_ids[&edge.from], edge.provenance, mermaid_ids[&edge.to]
        ));
    }
    output.push_str("  classDef phase fill:#eef4ff,stroke:#496a9f\n");
    output.push_str("  classDef algorithm fill:#fff7df,stroke:#8f6d1f\n");
    if !phases.is_empty() {
        output.push_str(&format!(
            "  class {} phase\n",
            phases
                .iter()
                .map(|phase| mermaid_ids[&phase.id].as_str())
                .collect::<Vec<_>>()
                .join(",")
        ));
    }
    if !algorithm_ids.is_empty() {
        output.push_str(&format!(
            "  class {} algorithm\n",
            algorithm_ids
                .iter()
                .map(|id| mermaid_ids[id].as_str())
                .collect::<Vec<_>>()
                .join(",")
        ));
    }
    output
}

/// Render the backend source-card inventory as a generated Markdown module map.
///
/// An algorithm is listed under every `k-rust-backend` source file that contains one of its
/// declared sites. Counter names come from the graph's `measured-by` edges, so the projection has
/// no inventory independent of the cards and registries.
pub fn render_module_map(graph: &Graph) -> String {
    let node_by_id = node_map(graph);
    let counters = graph
        .edges
        .iter()
        .filter(|edge| edge.kind == "measured-by")
        .fold(BTreeMap::<&str, BTreeSet<&str>>::new(), |mut map, edge| {
            if let Some(counter) = node_by_id.get(edge.to.as_str()) {
                map.entry(edge.from.as_str())
                    .or_default()
                    .insert(counter.name.as_deref().unwrap_or(counter.id.as_str()));
            }
            map
        });
    let mut modules = BTreeMap::<String, BTreeSet<String>>::new();
    let mut module_counters = BTreeMap::<String, BTreeSet<String>>::new();
    for algorithm in graph.nodes.iter().filter(|node| node.kind == "algorithm") {
        let anchors = std::iter::once(&algorithm.anchor).chain(&algorithm.sites);
        for anchor in anchors.filter(|anchor| anchor.crate_name == "k-rust-backend") {
            let module = anchor
                .file
                .strip_prefix("crates/k-rust-backend/src/")
                .unwrap_or(&anchor.file)
                .to_owned();
            modules
                .entry(module.clone())
                .or_default()
                .insert(algorithm.id.clone());
            if let Some(measurements) = counters.get(algorithm.id.as_str()) {
                module_counters
                    .entry(module)
                    .or_default()
                    .extend(measurements.iter().map(|counter| (*counter).to_owned()));
            }
        }
    }

    let mut output = String::from(
        "<!-- generated by `algo-graph render module-map`; do not edit -->\n\n\
         | Module | Algorithm IDs | Counters |\n\
         |---|---|---|\n",
    );
    for (module, algorithms) in modules {
        let counter_list = module_counters
            .get(&module)
            .map(|values| values.iter().cloned().collect::<Vec<_>>().join(", "))
            .unwrap_or_else(|| "none".to_owned());
        output.push_str(&format!(
            "| `{}` | `{}` | `{}` |\n",
            markdown_cell(&module),
            algorithms
                .iter()
                .map(|id| markdown_cell(id))
                .collect::<Vec<_>>()
                .join("`, `"),
            markdown_cell(&counter_list),
        ));
    }
    output
}

/// Render algorithms, representation boundaries, relationships, and measurements.
pub fn render_composition(graph: &Graph, filters: &Filters) -> String {
    render_composition_with_focus(graph, filters, None)
}

/// Render one algorithm's representation neighbourhood and downstream dependency closure.
///
/// The closure follows derived `feeds` edges and declared `constrains` edges. Measurements of
/// every algorithm in the closure are retained as leaves. `feeds` edges exist only in this
/// projection: the canonical graph continues to store the local `produces` and `consumes` halves.
///
/// A focus id that is not an algorithm of the graph, or that the filters remove, is an error.
pub fn render_composition_focus(
    graph: &Graph,
    filters: &Filters,
    focus: &str,
) -> Result<String, crate::Error> {
    let node_by_id = node_map(graph);
    match node_by_id.get(focus) {
        None => {
            return Err(crate::Error::Invalid(format!(
                "--focus {focus}: no node with this id in the graph"
            )));
        }
        Some(node) if node.kind != "algorithm" => {
            return Err(crate::Error::Invalid(format!(
                "--focus {focus}: the node is a {}, not an algorithm",
                node.kind
            )));
        }
        Some(_) => {}
    }
    if !selected_algorithms(graph, filters, &node_by_id).contains(focus) {
        return Err(crate::Error::Invalid(format!(
            "--focus {focus}: the algorithm is removed by the --area, --phase, or --counter filters"
        )));
    }
    Ok(render_composition_with_focus(graph, filters, Some(focus)))
}

fn render_composition_with_focus(graph: &Graph, filters: &Filters, focus: Option<&str>) -> String {
    let node_by_id = node_map(graph);
    let selected = selected_algorithms(graph, filters, &node_by_id);
    let composition_edges = composition_edges(graph);
    let base_algorithms = focus.map_or(selected.clone(), |focus| {
        downstream_algorithms(focus, &selected, &composition_edges, &node_by_id)
    });
    let composition_kinds = [
        "consumes",
        "produces",
        "feeds",
        "variant-of",
        "falls-back-to",
        "constrains",
        "measured-by",
    ];
    let mut visible_ids = base_algorithms.clone();
    for edge in composition_edges
        .iter()
        .filter(|edge| composition_kinds.contains(&edge.kind.as_str()))
    {
        let algorithm_relation = node_by_id
            .get(edge.from.as_str())
            .is_some_and(|node| node.kind == "algorithm")
            && node_by_id
                .get(edge.to.as_str())
                .is_some_and(|node| node.kind == "algorithm");
        if (algorithm_relation
            && base_algorithms.contains(&edge.from)
            && base_algorithms.contains(&edge.to))
            || (!algorithm_relation
                && (base_algorithms.contains(&edge.from) || base_algorithms.contains(&edge.to)))
            || (edge.kind == "constrains" && focus.is_none() && filters == &Filters::default())
        {
            visible_ids.insert(edge.from.clone());
            visible_ids.insert(edge.to.clone());
        }
    }
    let mut visible = visible_ids
        .iter()
        .filter_map(|id| node_by_id.get(id).copied())
        .collect::<Vec<_>>();
    visible.sort_by(|left, right| left.id.cmp(&right.id));
    let mermaid_ids = mermaid_ids(visible.iter().copied());
    let edges = composition_edges
        .iter()
        .filter(|edge| composition_kinds.contains(&edge.kind.as_str()))
        .filter(|edge| visible_ids.contains(&edge.from) && visible_ids.contains(&edge.to))
        .collect::<Vec<_>>();

    let mut output = String::new();
    output.push_str("%% generated by algo-graph; edge labels include provenance\n");
    output.push_str("flowchart LR\n");
    for node in &visible {
        let id = &mermaid_ids[&node.id];
        let text = label(&node.id);
        match node.kind.as_str() {
            "algorithm" => output.push_str(&format!("  {id}([\"{text}\"])\n")),
            "representation" => output.push_str(&format!("  {id}[[\"{text}\"]]\n")),
            "observation" => output.push_str(&format!("  {id}{{{{\"{text}\"}}}}\n")),
            "contract" => output.push_str(&format!("  {id}[/\"{text}\"/]\n")),
            "registry" => output.push_str(&format!("  {id}[(\"{text}\")]\n")),
            _ => output.push_str(&format!("  {id}[\"{text}\"]\n")),
        }
    }
    let mut constraint_links = Vec::new();
    for (index, edge) in edges.into_iter().enumerate() {
        let arrow = match (edge.kind.as_str(), edge.provenance.as_str()) {
            ("constrains", _) => {
                constraint_links.push(index);
                "-.->"
            }
            (_, "declared") => "-->",
            (_, "derived") => "-.->",
            (_, "table") => "==>",
            _ => "-->",
        };
        let detail = edge
            .detail
            .as_deref()
            .map(|detail| format!("<br/>{}", label(detail)))
            .unwrap_or_default();
        output.push_str(&format!(
            "  {} {arrow}|\"{} [{}]{detail}\"| {}\n",
            mermaid_ids[&edge.from], edge.kind, edge.provenance, mermaid_ids[&edge.to]
        ));
    }
    output.push_str("  classDef algorithm fill:#fff7df,stroke:#8f6d1f\n");
    output.push_str("  classDef representation fill:#e9f7ef,stroke:#39734f\n");
    output.push_str("  classDef observation fill:#f5edff,stroke:#73539a\n");
    output.push_str("  classDef contract fill:#fff0f6,stroke:#a23c6f\n");
    output.push_str("  classDef registry fill:#edf2f7,stroke:#52606d\n");
    for kind in [
        "algorithm",
        "representation",
        "observation",
        "contract",
        "registry",
    ] {
        let ids = visible
            .iter()
            .filter(|node| node.kind == kind)
            .map(|node| mermaid_ids[&node.id].as_str())
            .collect::<Vec<_>>();
        if !ids.is_empty() {
            output.push_str(&format!("  class {} {kind}\n", ids.join(",")));
        }
    }
    if !constraint_links.is_empty() {
        output.push_str(&format!(
            "  linkStyle {} stroke:#a23c6f,stroke-width:2px,stroke-dasharray:8 4\n",
            constraint_links
                .iter()
                .map(usize::to_string)
                .collect::<Vec<_>>()
                .join(",")
        ));
    }
    output
}

fn composition_edges(graph: &Graph) -> Vec<crate::Edge> {
    let mut edges = graph.edges.clone();
    let mut producers = BTreeMap::<&str, BTreeSet<&str>>::new();
    let mut consumers = BTreeMap::<&str, BTreeSet<&str>>::new();
    for edge in &graph.edges {
        match edge.kind.as_str() {
            "produces" => {
                producers
                    .entry(edge.to.as_str())
                    .or_default()
                    .insert(edge.from.as_str());
            }
            "consumes" => {
                consumers
                    .entry(edge.to.as_str())
                    .or_default()
                    .insert(edge.from.as_str());
            }
            _ => {}
        }
    }
    for (representation, producers) in producers {
        let Some(consumers) = consumers.get(representation) else {
            continue;
        };
        for producer in &producers {
            for consumer in consumers {
                if producer == consumer {
                    continue;
                }
                edges.push(crate::Edge {
                    kind: "feeds".to_owned(),
                    from: (*producer).to_owned(),
                    to: (*consumer).to_owned(),
                    provenance: "derived".to_owned(),
                    detail: Some(representation.to_owned()),
                    order: None,
                    consumer_site: None,
                });
            }
        }
    }
    edges.sort();
    edges.dedup();
    edges
}

fn downstream_algorithms(
    focus: &str,
    selected: &BTreeSet<String>,
    edges: &[crate::Edge],
    node_by_id: &BTreeMap<String, &Node>,
) -> BTreeSet<String> {
    if !selected.contains(focus)
        || !node_by_id
            .get(focus)
            .is_some_and(|node| node.kind == "algorithm")
    {
        return BTreeSet::new();
    }

    let mut closure = BTreeSet::from([focus.to_owned()]);
    let mut pending = vec![focus.to_owned()];
    // Invariant: `closure` holds `focus` and every selected algorithm reached so far over `feeds` or `constrains` edges, and `pending` holds the members of `closure` whose outgoing edges are unscanned; an id is pushed only when `closure.insert` admits it, so each id is popped at most once.
    while let Some(current) = pending.pop() {
        for edge in edges.iter().filter(|edge| {
            matches!(edge.kind.as_str(), "feeds" | "constrains") && edge.from == current
        }) {
            if selected.contains(&edge.to)
                && node_by_id
                    .get(edge.to.as_str())
                    .is_some_and(|node| node.kind == "algorithm")
                && closure.insert(edge.to.clone())
            {
                pending.push(edge.to.clone());
            }
        }
    }
    closure
}

fn selected_algorithms(
    graph: &Graph,
    filters: &Filters,
    node_by_id: &BTreeMap<String, &Node>,
) -> BTreeSet<String> {
    let mut selected = graph
        .nodes
        .iter()
        .filter(|node| node.kind == "algorithm")
        .filter(|algorithm| {
            filters.areas.is_empty()
                || algorithm
                    .area
                    .as_deref()
                    .is_some_and(|area| matches_any(area, &filters.areas))
        })
        .map(|node| node.id.clone())
        .collect::<BTreeSet<_>>();

    if !filters.phases.is_empty() {
        let in_phase = graph
            .edges
            .iter()
            .filter(|edge| edge.kind == "contains")
            .filter(|edge| matches_any(&edge.from, &filters.phases))
            .map(|edge| edge.to.clone())
            .collect::<BTreeSet<_>>();
        selected.retain(|id| in_phase.contains(id));
    }
    if !filters.counters.is_empty() {
        let measured = graph
            .edges
            .iter()
            .filter(|edge| edge.kind == "measured-by")
            .filter(|edge| {
                node_by_id.get(edge.to.as_str()).is_some_and(|counter| {
                    counter.kind == "observation"
                        && (matches_any(&counter.id, &filters.counters)
                            || counter
                                .name
                                .as_deref()
                                .is_some_and(|name| matches_any(name, &filters.counters))
                            || counter
                                .registry_name
                                .as_deref()
                                .is_some_and(|name| matches_any(name, &filters.counters)))
                })
            })
            .map(|edge| edge.from.clone())
            .collect::<BTreeSet<_>>();
        selected.retain(|id| measured.contains(id));
    }
    selected
}

fn node_map(graph: &Graph) -> BTreeMap<String, &Node> {
    graph
        .nodes
        .iter()
        .map(|node| (node.id.clone(), node))
        .collect()
}

fn matches_any(value: &str, choices: &[String]) -> bool {
    choices.iter().any(|choice| value == choice)
}

fn mermaid_ids<'a>(nodes: impl IntoIterator<Item = &'a Node>) -> BTreeMap<String, String> {
    nodes
        .into_iter()
        .enumerate()
        .map(|(index, node)| (node.id.clone(), format!("n{index:04}")))
        .collect()
}

fn label(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('"', "&quot;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('\n', " ")
}

fn markdown_cell(value: &str) -> String {
    value.replace('|', "\\|").replace('\n', " ")
}

#[cfg(test)]
mod tests {
    use crate::{Anchor, Edge, Graph, Node, build_graph, workspace_root};

    use super::*;

    #[test]
    fn renders_are_deterministic() {
        let graph = build_graph(&workspace_root()).unwrap().graph;
        let filters = Filters::default();
        assert_eq!(
            render_pipeline(&graph, &filters),
            render_pipeline(&graph, &filters)
        );
        assert_eq!(
            render_composition(&graph, &filters),
            render_composition(&graph, &filters)
        );
        assert_eq!(render_module_map(&graph), render_module_map(&graph));
    }

    #[test]
    fn module_map_is_derived_from_backend_sites_and_measurements() {
        let graph = build_graph(&workspace_root()).unwrap().graph;
        let rendered = render_module_map(&graph);
        assert!(rendered.contains("| `matching/mod.rs` |"));
        assert!(rendered.contains("backend.matching.syntactic"));
        assert!(rendered.contains("MatchingProblems"));
        assert!(!rendered.contains("parser.grammar.build"));
    }

    #[test]
    fn area_filter_limits_algorithms() {
        let graph = build_graph(&workspace_root()).unwrap().graph;
        let rendered = render_composition(
            &graph,
            &Filters {
                areas: vec!["backend".to_owned()],
                ..Filters::default()
            },
        );
        assert!(rendered.contains("backend.matching.syntactic"));
        assert!(!rendered.contains("parser.grammar.build"));
    }

    #[test]
    fn parser_focus_reaches_kompile_backend_and_their_counters() {
        let graph = build_graph(&workspace_root()).unwrap().graph;
        let rendered =
            render_composition_focus(&graph, &Filters::default(), "parser.bubble.rules").unwrap();
        assert!(rendered.contains("kompile.kore.declarations"));
        assert!(rendered.contains("backend.definition.internalize"));
        assert!(rendered.contains("backend.rewrite.execute"));
        assert!(rendered.contains("RewriteSteps"));
    }

    #[test]
    fn feeds_require_an_exact_representation_identity() {
        let graph = Graph {
            edges: vec![
                relation("produces", "producer", "crate::Term [configuration]"),
                relation("consumes", "matching", "crate::Term [configuration]"),
                relation("consumes", "other-role", "crate::Term [predicate]"),
            ],
            ..Graph::default()
        };

        let feeds = composition_edges(&graph)
            .into_iter()
            .filter(|edge| edge.kind == "feeds")
            .collect::<Vec<_>>();
        assert_eq!(feeds.len(), 1);
        assert_eq!(feeds[0].from, "producer");
        assert_eq!(feeds[0].to, "matching");
        assert_eq!(
            feeds[0].detail.as_deref(),
            Some("crate::Term [configuration]")
        );
        assert!(graph.edges.iter().all(|edge| edge.kind != "feeds"));
    }

    #[test]
    fn focus_renders_downstream_feeds_constraints_and_measurements() {
        let graph = Graph {
            nodes: vec![
                node("algorithm", "parser", Some("parser")),
                node("algorithm", "kompile", Some("kompile")),
                node("algorithm", "backend", Some("backend")),
                node("algorithm", "wrong-role", Some("backend")),
                node("representation", "crate::Term [parsed]", None),
                node("representation", "crate::Term [predicate]", None),
                node("observation", "counter.backend", None),
            ],
            edges: vec![
                relation("produces", "parser", "crate::Term [parsed]"),
                relation("consumes", "kompile", "crate::Term [parsed]"),
                relation("consumes", "wrong-role", "crate::Term [predicate]"),
                relation("constrains", "kompile", "backend"),
                relation("measured-by", "backend", "counter.backend"),
            ],
        };

        let rendered = render_composition_focus(&graph, &Filters::default(), "parser").unwrap();
        assert!(rendered.contains("parser"));
        assert!(rendered.contains("kompile"));
        assert!(rendered.contains("backend"));
        assert!(rendered.contains("counter.backend"));
        assert!(rendered.contains("feeds [derived]"));
        assert!(!rendered.contains("wrong-role"));
        assert!(!rendered.contains("crate::Term [predicate]"));
    }

    #[test]
    fn focus_rejects_unknown_non_algorithm_and_filtered_ids() {
        let graph = Graph {
            nodes: vec![
                node("algorithm", "parser.a", Some("parser")),
                node("observation", "counter.a", None),
            ],
            edges: Vec::new(),
        };
        for (focus, filters) in [
            ("parser.missing", Filters::default()),
            ("counter.a", Filters::default()),
            (
                "parser.a",
                Filters {
                    areas: vec!["backend".to_owned()],
                    ..Filters::default()
                },
            ),
        ] {
            let error = render_composition_focus(&graph, &filters, focus).unwrap_err();
            assert!(error.to_string().contains(focus), "{error}");
        }
    }

    #[test]
    fn pipeline_contains_edges_point_at_the_algorithm_with_provenance_in_the_label() {
        let mut phase = node("phase", "stage", Some("kompile"));
        phase.call = Some("run".to_owned());
        phase.sequence = Some(0);
        let mut contains = relation("contains", "stage", "kompile.a");
        contains.provenance = "derived".to_owned();
        let graph = Graph {
            nodes: vec![phase, node("algorithm", "kompile.a", Some("kompile"))],
            edges: vec![contains],
        };
        let rendered = render_pipeline(&graph, &Filters::default());
        assert!(
            rendered.contains("  n0001 -.->|\"contains [derived]\"| n0000\n"),
            "{rendered}"
        );
    }

    #[test]
    fn constraints_use_a_distinct_dashed_link_style() {
        let graph = build_graph(&workspace_root()).unwrap().graph;
        let rendered = render_composition(&graph, &Filters::default());
        let constraint_lines = rendered
            .lines()
            .filter(|line| line.contains("constrains [declared]"))
            .collect::<Vec<_>>();
        assert_eq!(constraint_lines.len(), 9);
        assert!(constraint_lines.iter().all(|line| line.contains("-.->")));
        assert!(rendered.contains("feeds [derived]"));
        assert!(rendered.contains("stroke:#a23c6f,stroke-width:2px,stroke-dasharray:8 4"));
        assert!(rendered.contains("classDef contract"));
        assert!(rendered.contains("classDef registry"));
    }

    fn relation(kind: &str, from: &str, to: &str) -> Edge {
        Edge {
            kind: kind.to_owned(),
            from: from.to_owned(),
            to: to.to_owned(),
            provenance: "declared".to_owned(),
            detail: None,
            order: None,
            consumer_site: None,
        }
    }

    fn node(kind: &str, id: &str, area: Option<&str>) -> Node {
        Node {
            kind: kind.to_owned(),
            id: id.to_owned(),
            provenance: "declared".to_owned(),
            anchor: Anchor {
                crate_name: "test".to_owned(),
                file: "test.rs".to_owned(),
                symbol: id.to_owned(),
            },
            area: area.map(ToOwned::to_owned),
            name: None,
            sites: Vec::new(),
            cost: Vec::new(),
            variable: None,
            invariant: None,
            no_counter: None,
            span: None,
            table: None,
            call: None,
            behavior: None,
            generating_passes: Vec::new(),
            type_path: None,
            role: None,
            registry_name: None,
            sequence: None,
        }
    }
}
