[package]
name = "k-rust-backend"
version = "0.3.0"
edition = "2024"
rust-version = "1.85"
description = "An in-process symbolic execution backend for k-rust"
repository = "https://github.com/midnightntwrk/k-rust"
license = "BSD-3-Clause"
keywords = ["k-framework", "kore", "rewriting", "symbolic-execution"]
categories = ["compilers", "development-tools"]

[dependencies]
k-rust-kore.workspace = true
k256.workspace = true
num-bigint.workspace = true
num-traits.workspace = true
petgraph.workspace = true
ripemd.workspace = true
rustc-hash.workspace = true
sha2.workspace = true
sha3.workspace = true
z3 = { workspace = true, optional = true }

[dev-dependencies]
indoc.workspace = true
proptest.workspace = true

[features]
z3 = ["dep:z3"]
